language: node_js
sudo: required

os:
  - windows
  - linux

node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"

before_install:
  - |-
    case $TRAVIS_OS_NAME in
      linux)
        if [[ ! -f stunnel.tar.gz ]]; then wget -O stunnel.tar.gz ftp://ftp.stunnel.org/stunnel/archive/5.x/stunnel-5.54.tar.gz; fi
        if [[ ! -f ./stunnel-5.54/configure ]]; then tar -xzf stunnel.tar.gz; fi
        if [[ ! -f ./stunnel-5.54/src/stunnel ]]; then cd ./stunnel-5.54; ./configure; make; cd ..; fi
        export PATH="$PATH:$(pwd)/stunnel-5.54/src"
    ;;
    esac
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install redis-64
        redis-server --service-install
        redis-server --service-start
        redis-cli config set stop-writes-on-bgsave-error no
    ;;
    esac

cache:
  directories:
    - "$HOME/AppData/Local/Temp/chocolatey"
    - "$TRAVIS_BUILD_DIR/stunnel-5.54"

after_success: npm run coveralls
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
